Describe cluster display tabs
QingCloudAppcenter/developer-guide pull request #38
Opened 2017-09-30 03:43 UTC by zryfish

Add documentation for display_tabs configuration

2017-09-30 07:00 UTC, chilianyi commented on developer/docs/specifications/specifications.md
> +	- timeout 非必填项，命令执行的timeout时长，单位ms，最大值和默认值为10，如果命令执行时长超过最大值将被终止。
这里单位是s吧.

2017-09-30 07:02 UTC, zryfish commented on developer/docs/specifications/specifications.md
> +	- timeout 非必填项，命令执行的timeout时长，单位ms，最大值和默认值为10，如果命令执行时长超过最大值将被终止。
是的

2017-09-30 07:04 UTC, chilianyi commented on developer/docs/specifications/specifications.md
> +	开发者可以配置此项以在集群详情页显示更多的自定义信息。例如，集群发生主从切换后，节点新的主从信息，节点新的状态。配置应用于整个集群，不支持分角色定义。
我记得代码里面是支持这个display_tabs定义到具体的role下面吧. 这样是在这个role里面随机选个节点执行, 否则是整个集群选择一个节点执行.

2017-09-30 07:08 UTC, zryfish commented on developer/docs/specifications/specifications.md
> +	开发者可以配置此项以在集群详情页显示更多的自定义信息。例如，集群发生主从切换后，节点新的主从信息，节点新的状态。配置应用于整个集群，不支持分角色定义。
是的，是可以配置到具体的Role下的，但是目前前端呈现会比较让人困惑，切换角色的话需要在节点列表中选择对应角色的节点，目前还是在集群层面配置好比较清晰些

2017-09-30 07:11 UTC, zryfish commented on developer/docs/specifications/specifications.md
> +	开发者可以配置此项以在集群详情页显示更多的自定义信息。例如，集群发生主从切换后，节点新的主从信息，节点新的状态。配置应用于整个集群，不支持分角色定义。
我觉得可以修改下配置，增加roles选择项，表示可以去哪些角色节点执行
```
display_tabs : {
     "roles" : ["master", "slave"],
     "node_details" : {
    }
}
```

2017-09-30 07:50 UTC, rayzhou2017 requested changes

2017-09-30 07:50 UTC, rayzhou2017 commented on developer/docs/specifications/specifications.md
> +		"node_details_tab": {
node_details_tab 和下面的node_authentication_tab是系统的key还是用户自定义的？

2017-09-30 08:20 UTC, zryfish commented on developer/docs/specifications/specifications.md
> +		"node_details_tab": {
用户自定义的，这里只是示例

2017-10-30 01:26 UTC, rayzhou2017 commented on developer/docs/specifications/specifications.md
> +	开发者可以配置此项以在集群详情页显示更多的自定义信息。例如，集群发生主从切换后，节点新的主从信息，节点新的状态。配置应用于整个集群，不支持分角色定义。
这个是已经上线了吗？

2017-10-31 03:59 UTC, zryfish commented on developer/docs/specifications/specifications.md
> +	开发者可以配置此项以在集群详情页显示更多的自定义信息。例如，集群发生主从切换后，节点新的主从信息，节点新的状态。配置应用于整个集群，不支持分角色定义。
更新到testing了，这周上线

2017-11-15 06:57 UTC, zryfish commented
@rayzhou2017 代码已经上线了，merge一下吧

2017-11-15 08:01 UTC, rayzhou2017 approved these changes

2017-11-15 08:01 UTC, merged